#!/bin/bash

wget -O /var/www/html/wp.tar.gz https://wordpress.org/latest.tar.gz
tar xf /var/www/html/wp.tar.gz -C /var/www/html/

cd ~
cd /var/www/html/
rm wp.tar.gz
cd /var/www/html/wordpress/
cp  wp-config-sample.php wp-config.php

sed 's/database_name_here/wordpress/' -i wp-config.php
sed 's/username_here/wpdbadmin/' -i wp-config.php

sed 's/password_here/verm5034/' -i wp-config.php
sed 's/localhost/wordpressdb.cvskchy784ur.us-west-2.rds.amazonaws.com/' -i wp-config.php

sed '/Directory \"\/var\/www\/html/,/AllowOverride None/s/AllowOverride None/AllowOverride All/' -i /etc/httpd/conf/httpd.conf

groupadd www
usermod -a -G www apache
chown -R apache:www /var/www
chmod 2775 /var/www
find /var/www -type d -exec chmod 2775 {} \;
find /var/www -type f -exec chmod 0664 {} \;

#Restart Apache web server
systemctl restart httpd.service

