---

- hosts: all
  become: yes
  become_method: sudo
  name: install apache
  tasks:
       - name: apache install
         yum: name=httpd state=latest
       - service: name=httpd enabled=yes
       - name: restart httpd in all instances
         service: name=httpd state=restarted
       - name: Installing php
         yum: name=php state=installed
       - name: Installing php-mysqlind
         yum: name=php-mysqlnd state=installed

- hosts: web1
  become: true
  become_method: sudo
  remote_user: ec2-user
  become_user: root
  name: install wordpress
  vars:
    database_name: '{{lookup("env","DATABASE_NAME")}}'
    database_username: '{{lookup("env","DATABASE_USERNAME")}}'
    database_password: '{{lookup("env","DATABASE_PASSWORD")}}'
    database_endpoint: '{{lookup("env","DATABASE_ENDPOINT")}}'
  tasks:
       - name: Install wordpress and copy it locally
         file: path=/var/www/html state=directory
       - name: Download wordpress
         get_url: url=https://wordpress.org/latest.tar.gz dest=/var/www/wp.tar.gz force=yes
       - name: un-archive
         unarchive: src=/var/www/wp.tar.gz dest=/var/www/html copy=no creates=/var/www/html/wordpress
       - name: wp-config.j2
         template: src=/home/ec2-user/ansible_templates/wp-config.j2 dest=/var/www/html/wordpress/wp-config.php